<?php
/**
 * Date.
 */

variable_set('date_default_timezone', 'America/Los_Angeles');
variable_set('date_first_day', 0);
variable_set('date_format_long', 'l, F j, Y - g:ia');
variable_set('date_format_medium', 'F j, Y - g:ia');
variable_set('date_format_short', 'M j Y - g:ia');

// Additional formats.
variable_set('date_format_long_notime', 'l, F j, Y');
variable_set('date_format_medium_notime', 'F j, Y');
variable_set('date_format_short_notime', 'M j Y');
variable_set('date_format_short_notime_noyear', 'M j');
