<?php
/**
 * External Links.
 */

variable_set('extlink_alert', 0);
variable_set('extlink_alert_text', 'This link will take you to an external web site.');
variable_set('extlink_class', 0);
variable_set('extlink_css_exclude', '');
variable_set('extlink_css_explicit', '');
variable_set('extlink_exclude', '');
variable_set('extlink_img_class', 0);
variable_set('extlink_include', '(.+\.(pdf|PDF))');
variable_set('extlink_mailto_class', 0);
variable_set('extlink_subdomains', 1);
variable_set('extlink_target', '_blank');
