<?php
/**
 * Pathauto.
 */

variable_set('pathauto_case', 1);
variable_set('pathauto_node_pattern', '[node:menu-link:parents:join-path]/[node:title]');
variable_set('pathauto_punctuation_ampersand', 0);
variable_set('pathauto_punctuation_asterisk', 0);
variable_set('pathauto_punctuation_at', 0);
variable_set('pathauto_punctuation_backtick', 0);
variable_set('pathauto_punctuation_back_slash', 0);
variable_set('pathauto_punctuation_caret', 0);
variable_set('pathauto_punctuation_colon', 1);
variable_set('pathauto_punctuation_comma', 2);
variable_set('pathauto_punctuation_dollar', 0);
variable_set('pathauto_punctuation_double_quotes', 0);
variable_set('pathauto_punctuation_equal', 0);
variable_set('pathauto_punctuation_exclamation', 0);
variable_set('pathauto_punctuation_greater_than', 0);
variable_set('pathauto_punctuation_hash', 0);
variable_set('pathauto_punctuation_hyphen', 1);
variable_set('pathauto_punctuation_left_curly', 0);
variable_set('pathauto_punctuation_left_parenthesis', 0);
variable_set('pathauto_punctuation_left_square', 0);
variable_set('pathauto_punctuation_less_than', 0);
variable_set('pathauto_punctuation_percent', 0);
variable_set('pathauto_punctuation_period', 2);
variable_set('pathauto_punctuation_pipe', 1);
variable_set('pathauto_punctuation_plus', 0);
variable_set('pathauto_punctuation_question_mark', 0);
variable_set('pathauto_punctuation_quotes', 0);
variable_set('pathauto_punctuation_right_curly', 0);
variable_set('pathauto_punctuation_right_parenthesis', 0);
variable_set('pathauto_punctuation_right_square', 0);
variable_set('pathauto_punctuation_semicolon', 0);
variable_set('pathauto_punctuation_slash', 0);
variable_set('pathauto_punctuation_tilde', 0);
variable_set('pathauto_punctuation_underscore', 2);
variable_set('pathauto_reduce_ascii', 1);
variable_set('pathauto_separator', '-');
variable_set('pathauto_transliterate', 1);
variable_set('pathauto_update_action', 2);
variable_set('pathauto_user_pattern', '');
variable_set('pathauto_ignore_words', '');
