<?php
/**
 * Redirect.
 */

variable_set('redirect_auto_redirect', 1);
variable_set('redirect_default_status_code', '301');
variable_set('redirect_global_admin_paths', 0);
variable_set('redirect_global_canonical', 1);
variable_set('redirect_global_clean', 1);
variable_set('redirect_global_deslash', 1);
variable_set('redirect_global_home', 1);
variable_set('redirect_page_cache', 0);
variable_set('redirect_passthrough_querystring', 1);
variable_set('redirect_purge_inactive', '15552000');
